variable "prefix" {}
variable "env" {}
variable "region" {}
variable "vpc_cidr_block" {}
variable "private_subnets" {}
variable "ecs_service_desired_count" {}
variable "ecr_crm_image_version" {}
variable "fargate_container_memory" {}
variable "fargate_container_cpu" {}
variable "app_port" {}
variable "admin_workstation_ip" {}